image: gitpod/workspace-full
  

ports:
  - port: 5000
    onOpen: open-preview


tasks:
  - init: 
      python -m venv venv &&
      venv/bin/pip install -r dev-requirements.txt && 
      venv/bin/python setup.py develop &&
      source venv/bin/activate
  