image: gitpod/workspace-full


ports:
  - port: 5000
    onOpen: open-browser


tasks:
  - init:
      export SKETCHBOOK_DIR=sketchbook &&
      python -m venv venv --system-site-packages &&
      venv/bin/pip install -r dev-requirements.txt &&
      venv/bin/python setup.py develop &&
      source venv/bin/activate &&
      pytest
    command: pyp5js serve
